### ISSUE TITLE
Sand zone teleportation crash

### ISSUE THREAD

**Issue by sgtpopper** [andwn/cave-story-md#76] opened 2016-12-08 17:17 UTC
Playing on the latest version, During the teleportation the game crashes to a screen saying ADDRESS ERROR ! I reset the emulator , tried a different emulator, Went out and in to the room, Teleported to a different room, It just crashes during the teleport to Sand Zone

**Comment by andwn** [comment] 2016-12-08 22:39
lastest version means the nightly?

**Comment by andwn** [comment] 2016-12-08 23:38
Ok I added a new release since I have been procrastinating to do so

https://github.com/andwn/cave-story-md/releases/tag/v0.3.0

0.2.1 had many random crash issues on real hardware as well as the more accurate emulators.

**Comment by andwhyisit** [comment] 2017-02-16 01:56
The teleportation glitch still happens, especially if you save in Jenka's house, reload, and then go immediately for the door.

Something tells me that this bug is related to the music engine, because if you wait for a bit then teleportation works fine.

**Comment by andwn** [comment] 2017-02-16 13:30
The issue you mention happens in the demo video. I've updated SGDK since then and will try to trigger it a few times. I also have a feeling the sound driver was responsible.

To explain the ADDRESS ERROR !  It was because I put the wrong number of frames for a sprite sheet in Sand Zone. Accurate emulators like GX and BlastEm threw this error while Gens did not.

**Comment by andwhyisit** [comment] 2017-02-23 12:04
Got the error in the previous nightly while entering Jenka's house. Once again the note being played exhibited infinite drag.

Here's the output:
![](http://i214.photobucket.com/albums/cc164/andwhyisit/jenkabrokethegame_zpsmqn4fikb.gif)

**Comment by andwhyisit** [comment] 2017-03-14 11:15
This one happened to me while using the door in the seal chamber. I can only reproduce in the PAL build.

This also only happens during the transition of the background music (Gestation) from the intro segment to the main loop.

Tested in gens.

**Comment by andwhyisit** [comment] 2017-03-14 11:24
Here's the output:
![](http://i214.photobucket.com/albums/cc164/andwhyisit/102thesequel_zps1xsuu5sd.gif)

Timing is everything as far as reproducing the error is concerned.

**Comment by andwhyisit** [comment] 2017-03-19 05:37
This one can be marked as complete.

**Closed** 2017-03-24 14:11 UTC
Labels: fix commited
